version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
	newline = true

	[[blocks.segments]]
		alias = 'User'
		type = 'text'
		style = 'plain'
		background = 'transparent'
		foreground = 'green'
		template = '{{ .UserName }}@{{ .HostName }} '

	[[blocks.segments]]
		alias = 'Path'
		type = 'path'
		style = 'plain'
		background = 'transparent'
		foreground = 'blue'
		template = '{{ .Path }} '
	
		[blocks.segments.properties]
			style = 'full'
	
	[[blocks.segments]]
		alias = 'Dollar'
		type = 'text'
		style = 'plain'
		background = 'transparent'
		foreground_templates = [
			"{{ if gt .Code 0 }}red{{ end }}",
			"{{ if eq .Code 0 }}magenta{{ end }}"
		]
		template = '$'

[transient_prompt]
		background = 'transparent'
		foreground = 'blue'
		template = "<green>{{ .UserName }}@{{ .HostName }}</> <blue>{{ .Segments.Path.Path }}</> <magenta>$</> "

