#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/ ~/Documents -mindepth 1 -maxdepth 1 -type d | /home/jorge@grazper.net/bin/fzf)
fi

if [[ -z $selected ]]; then
    sleep 2
    exit 0
fi

code $selected
