#!/bin/bash     

if (("$1" == 0 ))
    then
    xsetwacom set "Wacom Intuos BT M Pen stylus" MapToOutput eDP-1
    fi
if (("$1" == 1 ))
    then
    xsetwacom set "Wacom Intuos BT M Pen stylus" MapToOutput DP-3
    fi
