import = ["/home/yorch/.config/alacritty/themes/themes/catppuccin.toml"]
# import = ["/home/yorch/.config/alacritty/themes/themes/rose-pine-moon.toml"]
# import = ["/home/yorch/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 8

[font.bold]
family = "Roboto Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Roboto Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "Roboto Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 1000

[selection]
save_to_clipboard = true
